language: php
sudo: false
dist: trusty
php:
- 7.1
- 7.0
- 5.6
- nightly
env:
- TRAVIS_NODE_VERSION="6"
- TRAVIS_NODE_VERSION="7"
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
cache:
  apt: true
  directories:
  - $HOME/.composer/cache
  - $HOME/.yarn-cache
  - vendor
before_install:
- composer self-update
- gem install scss-lint
- source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
- export PATH=$HOME/.yarn/bin:$PATH && travis_retry curl -o- -L https://yarnpkg.com/install.sh
  | bash
install:
- node -v && yarn -V
- travis_retry yarn
- composer install -o --prefer-dist --no-interaction
- gem install sass
- gem install scss-lint
- npm install
- npm install -g gulp
script:
- gulp build
- composer test
notifications:
  slack: wildfirepublicity:Lw0t3aIPsbkmGhdO6TLc9wOA
